
module.exports = function RiotAPIData() {

	this.API_KEY = "a87fca94-3772-455d-a6df-e49033325d1e"

	this.HOSTS = {
		brazil              : 'br'   ,
		europe_nordic_east  : 'eune' ,
		europe_west         : 'euw'  ,
		korea               : 'kr'   ,
		latin_america_north : 'lan'  ,
		latin_america_south : 'las'  ,
		north_america       : 'na'   ,
		oceania             : 'oe'  ,
		russia              : 'ru'   ,
		turkey              : 'tr'   ,
	    
	    br   : 'br'   ,
	    eune : 'eune' ,
	    euw  : 'euw'  ,
	    kr   : 'kr'   ,
	    lan  : 'lan'  ,
	    las  : 'las'  ,
	    na   : 'na'   ,
	    oce  : 'oce'  ,
	    ru   : 'ru'   ,
	    ty   : 'tr'
	}

	this.PLATFORMS = {
	    brazil              : 'BR1'  ,
	    europe_nordic_east  : 'EUN1' ,
	    europe_west         : 'EUW1' ,
	    korea               : 'KR'   ,
	    latin_america_north : 'LA1'  ,
	    latin_america_south : 'LA2'  ,
	   	north_america       : 'NA1'  ,
	    oceania             : 'OC1'  ,
	    russia              : 'RU'   ,
	    turkey              : 'TR1'  ,

	    br   : 'BR1'  ,
	    eune : 'EUN1' ,
	    euw  : 'EUW1' ,
	    kr   : 'KR'   ,
	    lan  : 'LA1'  ,
	    las  : 'LA2'  ,
	    na   : 'NA1'  ,
	    oce  : 'OC1'  ,
	    ru   : 'RU'   ,
	    ty   : 'TR1'    
	}

	this.API_VERSIONS = {
	    champion        : "1.2",
	    current_game    : "1.0",
	    featured_games  : "1.0",
	    game            : "1.3",
	    league          : "2.5",
	    lol_static_data : "1.2",
	    lol_status      : "1.0",
	    match           : "2.2",
	    matchlist       : "2.2",
	    stats           : "1.3",
	    summoner        : "1.4",
	    team            : "2.4"
	}

	this.URLS = {
		base: "https://{host}.api.pvp.net/{url}",
		summoner: {
			base           : "api/lol/{region}/v{version}/summoner/{url}",
			by_name        : "by-name/{summonerNames}",
			by_ids         : "{summonerIds}",
			masteries_by_id: "{summonerIds}/masteries",
			name_by_id     : "{summonerIds}/name",
			runes_by_id    : "{summonerIds}/runes"
		},
		championmastery: {
			base  				    : "championmastery/location/{platformId}/player/{playerId}/{url}",
			single_champion_mastery : "champion/{championId}",
			all_champions_mastery   : "champions",
			total_score             : "score",
			top_champions           : "topchampions"
		},
		staticdata: {
			base      : "https://global.api.pvp.net/api/lol/{region}/v{version}/summoner/{url}",
			champions : "champion",
			champion  : "champion/{championId}"
		}
	}

	this.CHAMPIONS = {
		"35": "Shaco",
		"36": "DrMundo",
		"33": "Rammus",
		"34": "Anivia",
		"39": "Irelia",
		"157": "Yasuo",
		"37": "Sona",
		"38": "Kassadin",
		"154": "Zac",
		"150": "Gnar",
		"43": "Karma",
		"42": "Corki",
		"41": "Gangplank",
		"40": "Janna",
		"202": "Jhin",
		"203": "Kindred",
		"201": "Braum",
		"22": "Ashe",
		"23": "Tryndamere",
		"24": "Jax",
		"25": "Morgana",
		"26": "Zilean",
		"27": "Singed",
		"28": "Evelynn",
		"29": "Twitch",
		"3": "Galio",
		"161": "Velkoz",
		"2": "Olaf",
		"1": "Annie",
		"30": "Karthus",
		"7": "Leblanc",
		"6": "Urgot",
		"32": "Amumu",
		"5": "XinZhao",
		"31": "Chogath",
		"4": "TwistedFate",
		"9": "FiddleSticks",
		"8": "Vladimir",
		"19": "Warwick",
		"17": "Teemo",
		"18": "Tristana",
		"15": "Sivir",
		"16": "Soraka",
		"13": "Ryze",
		"14": "Sion",
		"11": "MasterYi",
		"12": "Alistar",
		"21": "MissFortune",
		"20": "Nunu",
		"107": "Rengar",
		"106": "Volibear",
		"105": "Fizz",
		"104": "Graves",
		"103": "Ahri",
		"102": "Shyvana",
		"99": "Lux",
		"101": "Xerath",
		"412": "Thresh",
		"98": "Shen",
		"96": "KogMaw",
		"222": "Jinx",
		"223": "TahmKench",
		"92": "Riven",
		"91": "Talon",
		"90": "Malzahar",
		"10": "Kayle",
		"429": "Kalista",
		"421": "RekSai",
		"420": "Illaoi",
		"89": "Leona",
		"117": "Lulu",
		"79": "Gragas",
		"78": "Poppy",
		"114": "Fiora",
		"115": "Ziggs",
		"77": "Udyr",
		"112": "Viktor",
		"113": "Sejuani",
		"110": "Varus",
		"111": "Nautilus",
		"119": "Draven",
		"432": "Bard",
		"82": "Mordekaiser",
		"245": "Ekko",
		"83": "Yorick",
		"80": "Pantheon",
		"81": "Ezreal",
		"86": "Garen",
		"84": "Akali",
		"85": "Kennen",
		"67": "Vayne",
		"126": "Jayce",
		"127": "Lissandra",
		"69": "Cassiopeia",
		"68": "Rumble",
		"121": "Khazix",
		"122": "Darius",
		"120": "Hecarim",
		"72": "Skarner",
		"236": "Lucian",
		"74": "Heimerdinger",
		"75": "Nasus",
		"238": "Zed",
		"76": "Nidalee",
		"134": "Syndra",
		"59": "JarvanIV",
		"133": "Quinn",
		"58": "Renekton",
		"57": "Maokai",
		"136": "AurelionSol",
		"56": "Nocturne",
		"55": "Katarina",
		"64": "LeeSin",
		"62": "MonkeyKing",
		"268": "Azir",
		"63": "Brand",
		"131": "Diana",
		"60": "Elise",
		"267": "Nami",
		"266": "Aatrox",
		"61": "Orianna",
		"143": "Zyra",
		"48": "Trundle",
		"45": "Veigar",
		"44": "Taric",
		"51": "Caitlyn",
		"53": "Blitzcrank",
		"54": "Malphite",
		"254": "Vi",
		"50": "Swain",

		Renekton: "58",
		Quinn: "133",
		Orianna: "61",
		MonkeyKing: "62",
		Brand: "63",
		LeeSin: "64",
		AurelionSol: "136",
		Vayne: "67",
		Rumble: "68",
		Cassiopeia: "69",
		Vi: "254",
		Jax: "24",
		Morgana: "25",
		Zilean: "26",
		Singed: "27",
		Nunu: "20",
		MissFortune: "21",
		Ashe: "22",
		Tryndamere: "23",
		Evelynn: "28",
		Twitch: "29",
		Jinx: "222",
		Olaf: "2",
		TwistedFate: "4",
		Urgot: "6",
		Vladimir: "8",
		Poppy: "78",
		Hecarim: "120",
		Elise: "60",
		Lux: "99",
		Shen: "98",
		Darius: "122",
		Nami: "267",
		Aatrox: "266",
		Jayce: "126",
		Lissandra: "127",
		Talon: "91",
		Malzahar: "90",
		Riven: "92",
		TahmKench: "223",
		Velkoz: "161",
		KogMaw: "96",
		MasterYi: "11",
		Kayle: "10",
		Ryze: "13",
		Alistar: "12",
		Sivir: "15",
		Sion: "14",
		Teemo: "17",
		Soraka: "16",
		Warwick: "19",
		Tristana: "18",
		Maokai: "57",
		Nocturne: "56",
		Caitlyn: "51",
		Diana: "131",
		Blitzcrank: "53",
		Katarina: "55",
		Thresh: "412",
		Malphite: "54",
		Zed: "238",
		Gnar: "150",
		Zac: "154",
		Yasuo: "157",
		Kalista: "429",
		Syndra: "134",
		Swain: "50",
		Ziggs: "115",
		Fiora: "114",
		Lulu: "117",
		Leona: "89",
		Nautilus: "111",
		Varus: "110",
		Sejuani: "113",
		Viktor: "112",
		Mordekaiser: "82",
		Yorick: "83",
		Pantheon: "80",
		Ezreal: "81",
		Draven: "119",
		Lucian: "236",
		Akali: "84",
		Kennen: "85",
		Azir: "268",
		Trundle: "48",
		Gragas: "79",
		Garen: "86",
		Taric: "44",
		Veigar: "45",
		Corki: "42",
		Karma: "43",
		Janna: "40",
		Gangplank: "41",
		Annie: "1",
		Galio: "3",
		XinZhao: "5",
		Leblanc: "7",
		FiddleSticks: "9",
		Illaoi: "420",
		Braum: "201",
		Kindred: "203",
		Jhin: "202",
		Zyra: "143",
		RekSai: "421",
		Udyr: "77",
		Nidalee: "76",
		Nasus: "75",
		Heimerdinger: "74",
		Skarner: "72",
		Shyvana: "102",
		Ahri: "103",
		Xerath: "101",
		Volibear: "106",
		Rengar: "107",
		Graves: "104",
		Fizz: "105",
		Ekko: "245",
		Irelia: "39",
		Kassadin: "38",
		Khazix: "121",
		Rammus: "33",
		Amumu: "32",
		Chogath: "31",
		Karthus: "30",
		Sona: "37",
		DrMundo: "36",
		Shaco: "35",
		Anivia: "34",
		JarvanIV: "59",
		Bard: "432"
	}
}